# Generated by Django 4.1.2 on 2022-10-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('entryType', models.CharField(max_length=10)),
                ('orderType', models.CharField(max_length=12)),
            ],
        ),
    ]
